/*
    GRUDGE Studio - AI Code Generator
    Generates scripts, scenes, UI components using AI
    Inspired by Vibe 8.0.0 AI-assisted development
*/

export class CodeGenerator {
    constructor() {
        this.templates = {}
        this.history = []
        this.context = {
            projectType: 'game',
            framework: 'three.js',
            language: 'javascript'
        }
        
        this.initTemplates()
    }
    
    initTemplates() {
        this.templates = {
            luaWeapon: {
                name: 'Lua Weapon Script',
                description: 'Creates a weapon behavior script with attacks and abilities',
                template: (params) => `-- ${params.name} Weapon Script
-- Generated by GRUDGE Studio

local ${params.className} = {
    name = "${params.name}",
    type = "${params.weaponType || 'melee'}",
    baseDamage = ${params.damage || 25},
    attackSpeed = ${params.attackSpeed || 1.0},
    range = ${params.range || 2.5},
    staminaCost = ${params.staminaCost || 10},
    
    animations = {
        idle = "${params.name.toLowerCase()}_idle",
        attack1 = "${params.name.toLowerCase()}_attack_1",
        attack2 = "${params.name.toLowerCase()}_attack_2",
        heavy = "${params.name.toLowerCase()}_heavy",
        block = "${params.name.toLowerCase()}_block"
    }
}

function ${params.className}:init()
    log("${params.name} initialized")
end

function ${params.className}:lightAttack()
    local stamina = Player.getStamina()
    if stamina < self.staminaCost then
        log("Not enough stamina!")
        return false
    end
    
    local target = Combat.getTarget()
    if target and target.distance <= self.range then
        Animation.play(self.animations.attack1)
        Player.modifyStamina(-self.staminaCost)
        
        Game.setTimeout(function()
            local damage = self.baseDamage * (1 + Player.getStat("strength") * 0.02)
            Combat.dealDamage(target.id, damage, "${params.damageType || 'physical'}")
        end, 0.3)
        
        return true
    end
    return false
end

function ${params.className}:heavyAttack()
    local stamina = Player.getStamina()
    if stamina < self.staminaCost * 2 then
        log("Not enough stamina for heavy attack!")
        return false
    end
    
    local target = Combat.getTarget()
    if target and target.distance <= self.range * 1.2 then
        Animation.play(self.animations.heavy)
        Player.modifyStamina(-self.staminaCost * 2)
        
        Game.setTimeout(function()
            local damage = self.baseDamage * 2.5 * (1 + Player.getStat("strength") * 0.03)
            Combat.dealDamage(target.id, damage, "${params.damageType || 'physical'}")
        end, 0.5)
        
        return true
    end
    return false
end

function ${params.className}:block()
    Animation.play(self.animations.block)
    Combat.setBlocking(true)
end

function ${params.className}:update(dt)
    -- Called every frame while weapon is equipped
end

return ${params.className}
`
            },
            
            luaAbility: {
                name: 'Lua Ability Script',
                description: 'Creates a spell or ability script',
                template: (params) => `-- ${params.name} Ability Script
-- Generated by GRUDGE Studio

local ${params.className} = {
    name = "${params.name}",
    type = "${params.abilityType || 'spell'}",
    manaCost = ${params.manaCost || 20},
    cooldown = ${params.cooldown || 3.0},
    damage = ${params.damage || 50},
    range = ${params.range || 10},
    aoeRadius = ${params.aoeRadius || 0},
    
    lastCast = 0,
    animation = "${params.name.toLowerCase()}_cast"
}

function ${params.className}:canCast()
    local mana = Player.getMana()
    local now = Game.getTime()
    
    if mana < self.manaCost then
        log("Not enough mana!")
        return false
    end
    
    if now - self.lastCast < self.cooldown then
        local remaining = self.cooldown - (now - self.lastCast)
        log("Ability on cooldown: " .. string.format("%.1f", remaining) .. "s")
        return false
    end
    
    return true
end

function ${params.className}:cast()
    if not self:canCast() then
        return false
    end
    
    Animation.play(self.animation)
    Player.modifyMana(-self.manaCost)
    self.lastCast = Game.getTime()
    
    ${params.aoeRadius > 0 ? `
    -- AoE attack
    local playerPos = Player.getPosition()
    local targets = Combat.getTargetsInRadius(playerPos, self.aoeRadius)
    
    for _, target in ipairs(targets) do
        local distance = Math3D.distance(playerPos, target.position)
        local falloff = 1 - (distance / self.aoeRadius) * 0.5
        local damage = self.damage * falloff * (1 + Player.getStat("intelligence") * 0.03)
        Combat.dealDamage(target.id, damage, "${params.damageType || 'magic'}")
    end
    
    Game.spawnEffect("${params.effectType || 'explosion'}", playerPos, { radius = self.aoeRadius })
    ` : `
    -- Single target attack
    local target = Combat.getTarget()
    if target and target.distance <= self.range then
        local damage = self.damage * (1 + Player.getStat("intelligence") * 0.03)
        
        ${params.abilityType === 'projectile' ? `
        Combat.spawnProjectile({
            from = Player.getPosition(),
            to = target.position,
            speed = 20,
            damage = damage,
            damageType = "${params.damageType || 'magic'}",
            effect = "${params.effectType || 'fireball'}"
        })
        ` : `
        Game.setTimeout(function()
            Combat.dealDamage(target.id, damage, "${params.damageType || 'magic'}")
            Game.spawnEffect("${params.effectType || 'magic_impact'}", target.position)
        end, 0.4)
        `}
    end
    `}
    
    Game.playSound("${params.name.toLowerCase()}_cast")
    return true
end

function ${params.className}:getCooldownRemaining()
    local now = Game.getTime()
    local remaining = self.cooldown - (now - self.lastCast)
    return math.max(0, remaining)
end

return ${params.className}
`
            },
            
            luaCharacter: {
                name: 'Lua Character Script',
                description: 'Creates a character controller script',
                template: (params) => `-- ${params.name} Character Script
-- Generated by GRUDGE Studio

local ${params.className} = {
    name = "${params.name}",
    class = "${params.characterClass || 'warrior'}",
    
    stats = {
        health = ${params.health || 100},
        maxHealth = ${params.maxHealth || 100},
        mana = ${params.mana || 50},
        maxMana = ${params.maxMana || 50},
        stamina = ${params.stamina || 100},
        maxStamina = ${params.maxStamina || 100},
        
        strength = ${params.strength || 10},
        dexterity = ${params.dexterity || 10},
        intelligence = ${params.intelligence || 10},
        vitality = ${params.vitality || 10}
    },
    
    equipment = {
        weapon = nil,
        armor = nil,
        accessory = nil
    },
    
    state = "idle",
    isAlive = true
}

function ${params.className}:init()
    log("${params.name} spawned as ${params.characterClass || 'warrior'}")
    self:calculateDerivedStats()
end

function ${params.className}:calculateDerivedStats()
    local s = self.stats
    s.maxHealth = 50 + s.vitality * 10
    s.maxMana = 20 + s.intelligence * 5
    s.maxStamina = 50 + s.dexterity * 5
    
    s.physicalDamage = 5 + s.strength * 2
    s.magicDamage = 5 + s.intelligence * 2
    s.defense = s.vitality * 0.5
    s.evasion = s.dexterity * 0.5
    s.critChance = 5 + s.dexterity * 0.3
end

function ${params.className}:takeDamage(amount, damageType)
    if not self.isAlive then return end
    
    local defense = self.stats.defense
    if damageType == "magic" then
        defense = defense * 0.5
    end
    
    local finalDamage = math.max(1, amount - defense)
    self.stats.health = self.stats.health - finalDamage
    
    log(self.name .. " took " .. finalDamage .. " " .. damageType .. " damage")
    
    if self.stats.health <= 0 then
        self:die()
    end
    
    return finalDamage
end

function ${params.className}:heal(amount)
    if not self.isAlive then return end
    
    local oldHealth = self.stats.health
    self.stats.health = math.min(self.stats.maxHealth, self.stats.health + amount)
    local healed = self.stats.health - oldHealth
    
    log(self.name .. " healed for " .. healed)
    return healed
end

function ${params.className}:die()
    self.isAlive = false
    self.state = "dead"
    Animation.play("death")
    log(self.name .. " has died")
    emit("character:death", { name = self.name })
end

function ${params.className}:respawn(position)
    self.isAlive = true
    self.state = "idle"
    self.stats.health = self.stats.maxHealth
    self.stats.mana = self.stats.maxMana
    self.stats.stamina = self.stats.maxStamina
    
    if position then
        Player.setPosition(position)
    end
    
    log(self.name .. " respawned")
end

function ${params.className}:update(dt)
    if not self.isAlive then return end
    
    -- Regeneration
    local s = self.stats
    s.stamina = math.min(s.maxStamina, s.stamina + 10 * dt)
    s.mana = math.min(s.maxMana, s.mana + 2 * dt)
end

function ${params.className}:getStat(name)
    return self.stats[name] or 0
end

function ${params.className}:setStat(name, value)
    self.stats[name] = value
    self:calculateDerivedStats()
end

return ${params.className}
`
            },
            
            sceneConfig: {
                name: 'Scene Configuration',
                description: 'Creates a scene setup file',
                template: (params) => `/*
    ${params.name} Scene Configuration
    Generated by GRUDGE Studio
*/

export const ${params.className}Config = {
    name: "${params.name}",
    type: "${params.sceneType || 'gameplay'}",
    
    world: {
        size: { x: ${params.worldSize?.x || 100}, y: ${params.worldSize?.y || 50}, z: ${params.worldSize?.z || 100} },
        gravity: ${params.gravity || -9.81},
        ambientLight: "${params.ambientLight || '#404060'}",
        fogEnabled: ${params.fogEnabled ?? true},
        fogColor: "${params.fogColor || '#1a1a2e'}",
        fogNear: ${params.fogNear || 10},
        fogFar: ${params.fogFar || 100}
    },
    
    lighting: [
        {
            type: "directional",
            color: "${params.sunColor || '#fffaf0'}",
            intensity: ${params.sunIntensity || 1.5},
            position: { x: 50, y: 100, z: 50 },
            castShadow: true
        },
        {
            type: "ambient",
            color: "${params.ambientLight || '#404060'}",
            intensity: 0.4
        }
    ],
    
    camera: {
        type: "${params.cameraType || 'thirdPerson'}",
        fov: ${params.fov || 60},
        near: 0.1,
        far: 1000,
        position: { x: 0, y: 5, z: 10 }
    },
    
    terrain: {
        enabled: ${params.terrainEnabled ?? true},
        heightScale: ${params.heightScale || 20},
        segments: ${params.segments || 128},
        material: "${params.terrainMaterial || 'grass'}"
    },
    
    spawnPoints: [
        { name: "player", position: { x: 0, y: 1, z: 0 } },
        { name: "enemy1", position: { x: 10, y: 1, z: 10 } },
        { name: "enemy2", position: { x: -10, y: 1, z: 10 } }
    ],
    
    assets: [
        ${params.assets?.map(a => `{ type: "${a.type}", path: "${a.path}", position: { x: ${a.x || 0}, y: ${a.y || 0}, z: ${a.z || 0} } }`).join(',\n        ') || ''}
    ],
    
    scripts: [
        ${params.scripts?.map(s => `"${s}"`).join(',\n        ') || ''}
    ],
    
    audio: {
        ambient: "${params.ambientSound || ''}",
        music: "${params.backgroundMusic || ''}"
    }
}

export function setup${params.className}(engine) {
    const config = ${params.className}Config
    
    // Apply world settings
    engine.physics.setGravity(0, config.world.gravity, 0)
    
    // Setup lighting
    config.lighting.forEach(light => {
        engine.lighting.add(light)
    })
    
    // Setup camera
    engine.camera.setType(config.camera.type)
    engine.camera.setFOV(config.camera.fov)
    
    // Load terrain
    if (config.terrain.enabled) {
        engine.terrain.generate(config.terrain)
    }
    
    // Load assets
    config.assets.forEach(async (asset) => {
        await engine.assets.load(asset.path)
        engine.scene.add(asset)
    })
    
    // Load scripts
    config.scripts.forEach(script => {
        engine.scripts.load(script)
    })
    
    console.log(\`Scene "${config.name}" loaded\`)
}

export default ${params.className}Config
`
            },
            
            uiComponent: {
                name: 'UI Component',
                description: 'Creates a canvas-based UI component',
                template: (params) => `/*
    ${params.name} UI Component
    Generated by GRUDGE Studio
*/

export class ${params.className} {
    constructor(options = {}) {
        this.x = options.x || 0
        this.y = options.y || 0
        this.width = options.width || ${params.width || 200}
        this.height = options.height || ${params.height || 100}
        this.visible = options.visible ?? true
        this.alpha = options.alpha ?? 1
        
        this.style = {
            backgroundColor: options.backgroundColor || '${params.backgroundColor || '#1e1e2e'}',
            borderColor: options.borderColor || '${params.borderColor || '#3d3d5c'}',
            borderWidth: options.borderWidth || ${params.borderWidth || 2},
            borderRadius: options.borderRadius || ${params.borderRadius || 8},
            textColor: options.textColor || '${params.textColor || '#e0e0e0'}',
            fontSize: options.fontSize || ${params.fontSize || 14},
            fontFamily: options.fontFamily || 'Arial',
            padding: options.padding || ${params.padding || 10}
        }
        
        this.children = []
        this.parent = null
        this.data = options.data || {}
        
        this.onClick = options.onClick || null
        this.onHover = options.onHover || null
    }
    
    addChild(component) {
        component.parent = this
        this.children.push(component)
        return this
    }
    
    removeChild(component) {
        const index = this.children.indexOf(component)
        if (index > -1) {
            this.children.splice(index, 1)
            component.parent = null
        }
        return this
    }
    
    setPosition(x, y) {
        this.x = x
        this.y = y
        return this
    }
    
    setSize(width, height) {
        this.width = width
        this.height = height
        return this
    }
    
    setStyle(style) {
        Object.assign(this.style, style)
        return this
    }
    
    show() {
        this.visible = true
        return this
    }
    
    hide() {
        this.visible = false
        return this
    }
    
    toggle() {
        this.visible = !this.visible
        return this
    }
    
    containsPoint(x, y) {
        return x >= this.x && 
               x <= this.x + this.width && 
               y >= this.y && 
               y <= this.y + this.height
    }
    
    render(ctx) {
        if (!this.visible) return
        
        ctx.save()
        ctx.globalAlpha = this.alpha
        
        // Draw background
        if (this.style.backgroundColor) {
            ctx.fillStyle = this.style.backgroundColor
            this.drawRoundedRect(ctx, this.x, this.y, this.width, this.height, this.style.borderRadius)
            ctx.fill()
        }
        
        // Draw border
        if (this.style.borderWidth > 0) {
            ctx.strokeStyle = this.style.borderColor
            ctx.lineWidth = this.style.borderWidth
            this.drawRoundedRect(ctx, this.x, this.y, this.width, this.height, this.style.borderRadius)
            ctx.stroke()
        }
        
        // Draw content
        this.renderContent(ctx)
        
        // Render children
        this.children.forEach(child => child.render(ctx))
        
        ctx.restore()
    }
    
    renderContent(ctx) {
        // Override in subclass
    }
    
    drawRoundedRect(ctx, x, y, width, height, radius) {
        ctx.beginPath()
        ctx.moveTo(x + radius, y)
        ctx.lineTo(x + width - radius, y)
        ctx.quadraticCurveTo(x + width, y, x + width, y + radius)
        ctx.lineTo(x + width, y + height - radius)
        ctx.quadraticCurveTo(x + width, y + height, x + width - radius, y + height)
        ctx.lineTo(x + radius, y + height)
        ctx.quadraticCurveTo(x, y + height, x, y + height - radius)
        ctx.lineTo(x, y + radius)
        ctx.quadraticCurveTo(x, y, x + radius, y)
        ctx.closePath()
    }
    
    handleClick(x, y) {
        if (!this.visible || !this.containsPoint(x, y)) return false
        
        for (let i = this.children.length - 1; i >= 0; i--) {
            if (this.children[i].handleClick(x, y)) return true
        }
        
        if (this.onClick) {
            this.onClick(this)
            return true
        }
        
        return false
    }
    
    handleHover(x, y) {
        if (!this.visible) return false
        
        const isHovered = this.containsPoint(x, y)
        
        if (isHovered && this.onHover) {
            this.onHover(this, true)
        }
        
        this.children.forEach(child => child.handleHover(x, y))
        
        return isHovered
    }
    
    update(dt) {
        this.children.forEach(child => child.update(dt))
    }
    
    dispose() {
        this.children.forEach(child => child.dispose())
        this.children = []
        this.parent = null
    }
}

export default ${params.className}
`
            }
        }
    }
    
    generate(templateType, params) {
        const template = this.templates[templateType]
        if (!template) {
            throw new Error(`Unknown template type: ${templateType}`)
        }
        
        const result = {
            type: templateType,
            name: template.name,
            params: params,
            code: template.template(params),
            timestamp: Date.now()
        }
        
        this.history.push(result)
        
        return result
    }
    
    getTemplateList() {
        return Object.entries(this.templates).map(([key, template]) => ({
            id: key,
            name: template.name,
            description: template.description
        }))
    }
    
    getHistory() {
        return this.history
    }
    
    clearHistory() {
        this.history = []
    }
    
    exportCode(result, filename) {
        const blob = new Blob([result.code], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.href = url
        link.download = filename
        link.click()
        URL.revokeObjectURL(url)
    }
}

export const codeGenerator = new CodeGenerator()
export default CodeGenerator
